### ISSUE TITLE
Failed to read password from /usr/bin/doveadm during login

### ISSUE THREAD

**Issue by AlphaJack** [postfixadmin/postfixadmin#419]
I just wanted to say that if you encounter an error like this in your webserver logs after updating to 3.3.0 you just need to make sure that the user which runs PHP has read permissions for that socket.

```
2021/01/13 19:30:47 [error] 17411#17411: *2581 FastCGI sent in stderr: "PHP message: Failed to read password from /usr/bin/doveadm pw ... stderr: doveadm(postfixadmin): Error: net_connect_unix(/run/dovecot/stats-writer) failed: Permission denied
, password: {SHA512-CRYPT}$6$HASH (verified)
 PHP message: PHP Fatal error:  Uncaught Exception: /usr/bin/doveadm pw failed, see error log for details in /usr/share/webapps/postfixadmin/functions.inc.php:1050
Stack trace:
#0 /usr/share/webapps/postfixadmin/functions.inc.php(1247): _pacrypt_dovecot('PASSWORD...', '{SHA512-CRYPT}$...')
#1 /usr/share/webapps/postfixadmin/model/Login.php(32): pacrypt('PASSWORD...', '{SHA512-CRYPT}$...')
#2 /usr/share/webapps/postfixadmin/public/login.php(63): Login->login('USERNAME...', 'PASSWORD...')
#3 {main}
  thrown in /usr/share/webapps/postfixadmin/functions.inc.php on line 1050" while reading response header from upstream, client: 127.0.0.1, server: postfixadmin, request: "POST /login.php HTTP/1.0", upstream: "fastcgi://unix:/run/postfixadmin/postfixadmin.sock:", host: "example.org"
```

In my case the command `ls -la /run/dovecot/stats-writer` returned:
```
srw-rw---- 1 root dovecot 0 Jan 12 21:41 /run/dovecot/stats-writer
```
so I appended the "dovecot" group to my Postfixadmin PHP user (yours could be "www-data") with `sudo usermod -aG dovecot postfixadmin`

**Comment by DavidGoodwin** [comment]
Thanks - I encountered the same while testing earlier today.
