### ISSUE TITLE
 ERROR: column "password_expiry" does not exist

### ISSUE THREAD

**Issue by CamZie** [postfixadmin/postfixadmin#531]
I upgraded PostfixAdmin version 2.9.1 to 3.3.10. I followed the upgrade guide, copied over the current config.local.php did the upgrade via setup.php  and everything went well with the database update:
```
Database is up to date: 1844/0 
```
The problem is, when I create or delete mailboxes after the upgrade I get the error below.

PHP error:

```
Fatal error: Uncaught Exception: DEBUG INFORMATION: SQLSTATE[42703]: Undefined column: 7 ERROR: column "password_expiry" does not exist LINE 1: ...m-dd') AS modified, modified AS _modified,TO_CHAR(password_e... ^<br/> Check your error_log for the failed query in /var/www/***REMOVED***/htdocs/postfixadmin-postfixadmin-3.3.10/functions.inc.php:1859 Stack trace: 
#0 /var/www/***REMOVED***/htdocs/postfixadmin-postfixadmin-3.3.10/functions.inc.php(1798): db_query(' SELECT usernam...', Array) 
#1 /var/www/***REMOVED***/htdocs/postfixadmin-postfixadmin-3.3.10/model/PFAHandler.php(772): db_query_all(' SELECT usernam...') 
#2 /var/www/***REMOVED***/htdocs/postfixadmin-postfixadmin-3.3.10/model/PFAHandler.php(800): PFAHandler->read_from_db(Array) 
#3 /var/www/***REMOVED***/htdocs/postfixadmin-postfixadmin-3.3.10/model/PFAHandler.php(350): PFAHandler->view(false) 
#4 /var/www/***REMOVED***/htdocs/postfixadmin-postfixadmin-3.3.10/model/MailboxHandler.php(64): PFAHandler->init('***REMOVED***....') 
#5 /var/www/***REMOVED***/htdocs/postfixad in /var/www/***REMOVED***/htdocs/postfixadmin-postfixadmin-3.3.10/functions.inc.php on line 1859
```

Database error:
```
2021-08-20 15:24:17.992 CEST [1261] ***REMOVED***@postfix ERROR:  column "password_expiry" does not exist at character 357

2021-08-20 15:24:17.992 CEST [1261] ***REMOVED***@postfix STATEMENT:   SELECT username,local_part,domain,maildir,password,password as password2,name,quota,CASE active WHEN 't' THEN '1'    WHEN 'f' THEN '0'   END as active,CASE active WHEN 't' THEN 'YES' WHEN 'f' THEN 'NO' END as _active,TO_CHAR(created, 'YYYY-mm-dd') AS created, created AS _created,TO_CHAR(modified, 'YYYY-mm-dd') AS modified, modified AS _modified,TO_CHAR(password_expiry, 'YYYY-mm-dd') AS password_expiry, password_expiry AS _password_expiry,1 as _can_edit,1 as _can_delete  FROM mailbox   WHERE 1=1   AND  domain IN (.......)
```

Our postfix mailbox table does not have the `password_expiry` column so we have added the following parameter in the `config.local.php` . Am I missing something?
```
$CONF['password_expiration'] = 'NO';
```

Thanks in advance for the help.

**Comment by DavidGoodwin** [comment]
Hm, well, public/upgrade.php has : 

https://github.com/postfixadmin/postfixadmin/blob/ecc97439abab24c7e67cfd351ac82ba220c0f489/public/upgrade.php#L1926

which should have triggered the addition of those columns

**Comment by CamZie** [comment]
It looks like the problem was insufficient permissions in the postfix database tables, which is the reason why there were no changes in the postfix tables. Somehow the upgrade.php and setup.php script did not recognise this error and just marked it as `Database is up to date: 1844/0 `

I deleted the postfix database and restored the one before the upgrade, corrected the permission and re-run the setup.php/upgrade.php and it works now.
