### ISSUE TITLE
php8: crypt() compatibility

### ISSUE THREAD

**Issue by zw3n** [postfixadmin/postfixadmin#547]
Got the following error when visiting `setup.php`. 
```
Got error 'PHP message: PHP Fatal error:  Uncaught ArgumentCountError: crypt() expects exactly 2 arguments, 1 given in /usr/share/webapps/postfixadmin/functions.inc.php:930
Stack trace:
#0 /usr/share/webapps/postfixadmin/functions.inc.php(930): crypt()
#1 /usr/share/webapps/postfixadmin/functions.inc.php(1263): _pacrypt_crypt()
#2 /usr/share/webapps/postfixadmin/public/setup.php(663): pacrypt()
#3 /usr/share/webapps/postfixadmin/public/setup.php(290): do_software_environment_check()
#4 {main}
  thrown in /usr/share/webapps/postfixadmin/functions.inc.php on line 930'
```
Looks like the second `crypt()`-parameter isn't optional since php 8.0.0: https://www.php.net/manual/en/function.crypt.php

**Comment by DavidGoodwin** [comment]
hopefully a fix should be in master, and on the postfixadmin_3.3 branch.

Thanks for reporting it!
