### ISSUE TITLE
Migrate from vimbadmin to postfixadmin

### ISSUE THREAD

**Issue by yodatak** [postfixadmin/postfixadmin#813]
Hi thanks for you awsome app we use vimbadmin but not is outdated and unmaintened we would like to migrate to vimbadmin is there a simple  way to migrate the database vimadmin to postfixadmin

 exemple with trying to update a vimadmin database ( verry similar)
```
 ** Running database / environment upgrade.php 
<p>Updating database:</p><p>- old version: 0; target version: 1847</p>


<div style='color:#999'>&nbsp;&nbsp;(If the update doesn't work, run setup.php?debug=1 to see the detailed error messages and SQL queries.)</div>
<p>updating to version 2 (PgSQL)...
Invalid query: SQLSTATE[42804]: Datatype mismatch: 7 ERREUR:  la contrainte de clé étrangère « vacation_domain_fkey » ne peut pas être implémentée
DETAIL:  Les colonnes clés « domain » et « id » sont de types incompatibles : character varying et bigint. caused by CREATE TABLE vacation (
                email character varying(255) PRIMARY KEY,
                subject character varying(255) NOT NULL,
                body text NOT NULL ,
                cache text NOT NULL ,
                "domain" character varying(255) NOT NULL REFERENCES "domain",
                created timestamp with time zone DEFAULT now(),
                active boolean DEFAULT true NOT NULL
            );
Exception running PostfixAdmin query: CREATE TABLE vacation (
                email character varying(255) PRIMARY KEY,
                subject character varying(255) NOT NULL,
                body text NOT NULL ,
                cache text NOT NULL ,
                "domain" character varying(255) NOT NULL REFERENCES "domain",
                created timestamp with time zone DEFAULT now(),
                active boolean DEFAULT true NOT NULL
            ); PDOException: SQLSTATE[42804]: Datatype mismatch: 7 ERREUR:  la contrainte de clé étrangère « vacation_domain_fkey » ne peut pas être implémentée
DETAIL:  Les colonnes clés « domain » et « id » sont de types incompatibles : character varying et bigint. in /var/www/html/functions.inc.php:1837
Stack trace:
#0 /var/www/html/functions.inc.php(1837): PDOStatement->execute(Array)
#1 /var/www/html/public/upgrade.php(329): db_execute('CREATE TABLE va...', Array, true)
#2 /var/www/html/public/upgrade.php(611): db_query_parsed('\n            CR...')
#3 /var/www/html/public/upgrade.php(220): upgrade_2_pgsql()
#4 /var/www/html/public/upgrade.php(154): _do_upgrade(0)
#5 {main}

Fatal error: Uncaught Exception: Postfixadmin DB update failed. Please check your PHP error_log in /var/www/html/public/upgrade.php:336
Stack trace:
#0 /var/www/html/public/upgrade.php(611): db_query_parsed('\n            CR...')
#1 /var/www/html/public/upgrade.php(220): upgrade_2_pgsql()
#2 /var/www/html/public/upgrade.php(154): _do_upgrade(0)
#3 {main}
  thrown in /var/www/html/public/upgrade.php on line 336
```

**Comment by DavidGoodwin** [comment]
Hi - I don't know anything about vimbadmin.

I assume you're trying to run Postfixadmin's install on top of an existing vimbadmin database.

The error message seems to be complaining about the table vacation_domain trying to have a foreign key to domain, when one field is a varchar but the other is a bigint, so this makes me think that vimbadmin's database structure is somewhat different from postfixadmins. Even if you fix this problem, I suspect you're going to hit other problems.

I think you'd be better off finding a way to export your current data (mailboxes, aliases etc) out of vimbadmin and then inserting it into postfixadmin - rather than trying to upgrade/reshape a vimbadmin database into what postfixadmin expects.

**Comment by neuffer** [comment]
@DavidGoodwin In the dark past it was forked from postfixadmin, IIRC.

**Comment by DavidGoodwin** [comment]
@neuffer yeah, but I don't have much interest in trying to write a migration routine :-)

**Comment by neuffer** [comment]
I agree. I had done that for a while after iRedmail  was forked from Postfixadmin.
Not fun.
